- docs/partner_editable/_settings.adoc
- docs/partner_editable/deploy_steps.adoc
Add 1 click deployment links to the documentation
> Add launch links to docs

- .cfnlintrc
- .override-spec.json
- templates/workload/gitlab-infra-template.yaml
- templates/workload/gitlab-telemetry-template.yaml
- templates/workload/gitlab-template.yaml
> Use the function ARN

- .gitmodules
> Remove branch tracking from third party submodule dependency

- .override-spec.json
> Values can be of any type. Resolve lint issues.

- .override-spec.json
- templates/workload/gitlab-infra-template.yaml
- templates/workload/gitlab-postinstall-template.yaml
> Add a missing parameter to the ACM cleanup custom resource

- .taskcat.yml
- templates/workload/gitlab-template.yaml
> Add a simple taskcat test to verify GovCloud deployment

- .taskcat.yml
- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
- templates/workload/gitlab-infra-template.yaml
- templates/workload/gitlab-praefect-template.yaml
- templates/workload/gitlab-secrets-template.yaml
- templates/workload/gitlab-template.yaml
*Issue #24 *
Random generated DB Password Reusing Smtp password CF function
> Random generated DB Password

- CODEOWNERS
> Adjustments for CI onboarding reqs

- .metadata
Specify language type for project
> Add required CI metadata file

- templates/gitlab-entry-existing-vpc.template.yaml
- templates/workload/gitlab-secrets-template.yaml
- templates/workload/gitlab-storage-template.yaml
- templates/workload/gitlab-template.yaml
*Issue #, if available:* #121
Replace IAM user with IAM role and k8s Service Account for S3 access.
See https://docs.gitlab.com/charts/advanced/external-object-storage/aws-iam-roles.html for details.
> Replace IAM user with IAM role and k8s Service Account for S3 access.

- .taskcat.yml
- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
Fix the order and descriptions for the database parameters. Update .taskcat.yaml to use smaller instance types during CI tests.
> Ensure that database parameters are properly documented

- .gitignore
> Ignore standard Quick Start directories + files

- .gitmodules
- templates/gitlab-entry-new-vpc.template.yaml
* Simplify and ensure consistency/compatibility with the EKS submodule
* Remove independent VPC submodule
> Use the VPC submodule of the EKS submodule

- .taskcat.yml
- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
*Issue #138 
Closes #138 
Validates that GitLab and Helm versions have been tested with and are known to work with the QuickStart automation.
> GL and helm version validation

- .taskcat.yml
Closes #139 
Relates to #144 
* Restore test regions
* Use regional S3 buckets (to make @DarwinJS's life easier 😃)
* Explicitly enable recursive taskcat code packaging
* Remove a couple of unnecessary taskcat settings
> Restore test regions

- .gitmodules
- .taskcat.yml
* Bumped to latest
* Combined since both have negligible changes
> Bump RDS & Aurora submodules to latest

- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
- templates/workload/gitlab-storage-template.yaml
- templates/workload/gitlab-template.yaml
*Issue #:*
* Closes #142 
* Implements part of #11
> Object storage KMS encryption support bug fix

- templates/workload/gitlab-secrets-template.yaml
* Existing secrets QSID duplicates the storage template QSID, and each should be unique https://github.com/aws-quickstart/quickstart-eks-gitlab/pull/149#pullrequestreview-1146625215
> Fix secrets template QSID

- Makefile
- scripts/init-submodules.sh
> Add makefile + init-submodules script

- templates/workload/gitlab-telemetry-template.yaml
> Use latest fluentd image by default

- .taskcat.yml
- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
- templates/workload/gitlab-database-template.yaml
- templates/workload/gitlab-template.yaml
*Issue #132 
- Get Gitlab 15 Working
Additional Todos:
> Gitlab 15.4 Updates

- docs/deployment_guide/partner_editable/_settings.adoc
- docs/deployment_guide/partner_editable/post_deployment.adoc
- docs/deployment_guide/partner_editable/pre_deployment.adoc
- docs/deployment_guide/partner_editable/troubleshooting.adoc
> TW edits for punct, links, rewording

- templates/gitlab-entry-existing-vpc.template.yaml
*Issue #, if available:* https://github.com/aws-quickstart/quickstart-amazon-eks/issues/418
*Description of changes:* 🤞 
> Bump EKS submodule to latest

- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
*Issue #, if available:* Closes #103 
> Add support for SSM-only access

- .gitmodules
- .taskcat.yml
- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
- templates/workload/gitlab-database-template.yaml
- templates/workload/gitlab-template.yaml
> Remove Aurora PostgreSQL submodule + config

- templates/gitlab-entry-existing-vpc.template.yaml
*Issue #, if available:* https://gitlab.com/groups/gitlab-org/-/epics/6883
Per discussion with @DarwinJS 
> Bump EKS version pin to 1.22

- templates/gitlab-entry-existing-vpc.template.yaml
> Enable prometheus integration

- templates/gitlab-entry-existing-vpc.template.yaml
- templates/gitlab-entry-new-vpc.template.yaml
- templates/workload/gitlab-cache-template.yaml
- templates/workload/gitlab-functions-template.yaml
- templates/workload/gitlab-postinstall-template.yaml
- templates/workload/gitlab-secrets-template.yaml
- templates/workload/gitlab-storage-template.yaml
- templates/workload/gitlab-template.yaml
> Add KMS option to entry points

- templates/workload/gitlab-infra-template.yaml
> Grant SES SMTP IAM user access to send email to any validated identity

- templates/gitlab-entry-existing-vpc.template.yaml
> Optimize pod footprint
